name: Continuous Integration (requirements)
permissions: read-all
on:
  pull_request:
    branches:
      - main
      - git_push_stack/**
jobs:
  requirements:
    timeout-minutes: 5
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout \U0001F6CE️"
        uses: actions/checkout@v2.4.0
      - name: "Setup Python \U0001F527"
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.10.2
      - name: "Build \U0001F527 & Test \U0001F50D"
        run: |
          pip install tox
          tox -e requirements
          tox -e missing-imports
          tox -e genreqs
          git diff --exit-code
