name: Upload production docs to GCP
on:
  push:
    branches:
      - main
jobs:
  docs-upload-to-gcp-prod:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout \U0001F6CE️"
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false
      - name: "Setup Python \U0001F527"
        uses: actions/setup-python@v2.3.2
        with:
          python-version: 3.10.2
      - name: "Setup Node \U0001F527"
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
      - name: "Build \U0001F527"
        run: |
          sudo apt-get install -y graphviz
          pip install tox
          tox -e docs
      - name: "Setup gcloud \U0001F527"
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_DOCS_EMAIL }}
          service_account_key: ${{ secrets.GCP_DOCS_KEY }}
          export_default_credentials: true
      - name: "Deploy \U0001F680"
        uses: google-github-actions/upload-cloud-storage@main
        with:
          path: docs/build
          destination: mergify-docs-prod
          parent: false
